## Creating tensors and accessing attributes

### Tensors are the primary data structure in PyTorch and will be the building blocks for our deep learning models. They share many similarities with NumPy arrays but have some unique attributes too.

### In this exercise, you'll practice creating a tensor from a Python list and displaying some of its attributes.

### Instructions 1/2
-    Begin by importing PyTorch.
-    Create a tensor from the Python list list_a

In [3]:
# Import PyTorch
import torch

list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)

print(tensor_a)

tensor([1, 2, 3, 4])


### Instructions 2/2
-    Display the tensor device.
-    Display the tensor data type.

In [4]:
# Import PyTorch
import torch

list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)

# Display the tensor device
print(tensor_a.device)

# Display the tensor data type
print(tensor_a.dtype)

cpu
torch.int64


## Creating tensors from NumPy arrays

### Tensors are the fundamental data structure of PyTorch. You can create complex deep learning algorithms by learning how to manipulate them.

### The torch package has been imported, and two NumPy arrays have been created, named array_a and array_b. Both arrays have the same dimensions.

### Instructions
-    Create two tensors, tensor_a and tensor_b, from the NumPy arrays array_a and array_b, respectively.
-    Subtract tensor_b from tensor_a.
-    Perform an element-wise multiplication of tensor_a and tensor_b.
-    Add the resulting tensors from the two previous steps together.

In [5]:
import numpy as np

array_a = np.array([[1, 1, 1],
       [2, 3, 4],
       [4, 5, 6]])

array_b = np.array([[7, 5, 4],
       [2, 2, 8],
       [6, 3, 8]])

In [6]:
# Create two tensors from the arrays
tensor_a = torch.tensor(array_a)
tensor_b = torch.tensor(array_b)

# Subtract tensor_b from tensor_a 
tensor_c = tensor_a - tensor_b

# Multiply each element of tensor_a with each element of tensor_b
tensor_d = tensor_a * tensor_b

# Add tensor_c with tensor_d
tensor_e = tensor_c + tensor_d
print(tensor_e)

tensor([[ 1,  1,  1],
        [ 4,  7, 28],
        [22, 17, 46]])


## Your first neural network

### In this exercise, you will implement a small neural network containing two linear layers. The first layer takes an eight-dimensional input, and the last layer outputs a one-dimensional tensor.

### The torch package and the torch.nn package have already been imported for you.

### Instructions
-    Create a neural network of linear layers that takes a tensor of dimensions 1x8 as input and outputs a tensor of dimensions 1x1.
-    Use any output dimension for the first layer you want.

In [7]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(nn.Linear(8, 1),
                      nn.Linear(1, 1)
                     )

output = model(input_tensor)
print(output)

tensor([[1.6708]], grad_fn=<AddmmBackward0>)


## The sigmoid and softmax functions

### The sigmoid and softmax functions are two of the most popular activation functions in deep learning. They are both usually used as the last step of a neural network. Sigmoid functions are used for binary classification problems, whereas softmax functions are often used for multi-class classification problems. This exercise will familiarize you with creating and using both functions.

### Let's say that you have a neural network that returned the values contained in the score tensor as a pre-activation output. You will apply activation functions to this output.

### torch.nn is already imported as nn.

### Instructions 1/2
-    Create a sigmoid function and apply it on input_tensor to generate a probability.

In [9]:
input_tensor = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on input_tensor
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)

tensor([[0.6900]])


### Instructions 2/2
-    Create a softmax function and apply it on input_tensor to generate a probability.

In [10]:
input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

# Create a softmax function and apply it on input_tensor
softmax = nn.Softmax(dim=-1)
probabilities = softmax(input_tensor)
print(probabilities)

tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])
